version: '3'

services:

    ##### POSTGRES #####
    db:
        restart: always
        build: ./db
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    ##### APP #####
    app:
        restart: on-failure
        build: ./shop_api
        ports:
          - 8000:8000
        command: bash -c "sleep 5 && python manage.py makemigrations 
                 && python manage.py migrate 
                 && python manage.py loaddata shop_samples.json 
                 && python manage.py loaddata product_samples.json
                 && python manage.py runserver 0.0.0.0:8000"
        depends_on:
          - db
