# Generated by Django 3.0.3 on 2020-02-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['owner']},
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='user',
            new_name='owner',
        ),
    ]
