# Generated by Django 3.0.3 on 2020-02-08 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket_app', '0003_discountsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountsModel',
            new_name='Discount',
        ),
    ]
