# Generated by Django 3.0.3 on 2020-02-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0005_auto_20200208_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
