# Generated by Django 3.0.3 on 2020-02-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0007_auto_20200208_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
