# Generated by Django 3.0.3 on 2020-02-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket_app', '0001_initial'),
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('basket', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basket_app.Basket')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Shop')),
            ],
            options={
                'ordering': ['name', 'price'],
            },
        ),
    ]
